/** @typedef {import('./project-types.js').Project} Project */

/** @type {ReadonlyArray<Project>} */
export const demoProjects = Object.freeze([
  {
    id: 'nova',
    title: "Nova — suivi d'habitudes",
    description: "Application mobile de suivi d'habitudes avec rappels et fonctionnement hors ligne.",
    languages: ['Flutter', 'Supabase'],
    difficulty: 'moyen',
    status: 'open',
    author: 'lea.codes',
    memberCount: 3,
    accent: 1,
  },
  {
    id: 'pixelforge',
    title: 'Pixelforge — éditeur de sprites',
    description: 'Éditeur de pixel art dans le navigateur destiné à la création de ressources de jeu.',
    languages: ['TypeScript', 'Canvas'],
    difficulty: 'facile',
    status: 'open',
    author: 'max_dev',
    memberCount: 2,
    accent: 2,
  },
  {
    id: 'cartel',
    title: 'Cartel — outil de veille en ligne de commande',
    description: 'Outil qui résume les nouveautés publiées sur une liste de dépôts GitHub.',
    languages: ['Rust'],
    difficulty: 'difficile',
    status: 'open',
    author: 'tigroubabar',
    memberCount: 1,
    accent: 3,
  },
  {
    id: 'lentille',
    title: 'Lentille — galerie photo auto-hébergée',
    description: 'Galerie personnelle pour classer des photos par lieu et par conditions de lumière.',
    languages: ['Python', 'React'],
    difficulty: 'moyen',
    status: 'full',
    author: 'nadia.k',
    memberCount: 4,
    accent: 4,
  },
  {
    id: 'sillage',
    title: 'Sillage — journal de développement',
    description: 'Extension de navigateur qui enregistre les changements d’un projet pour préparer un journal de versions.',
    languages: ['JavaScript'],
    difficulty: 'facile',
    status: 'open',
    author: 'yohan_b',
    memberCount: 2,
    accent: 5,
  },
  {
    id: 'boussole',
    title: 'Boussole — assistant de revue de code',
    description: "Bot Discord qui analyse les demandes de fusion avant la revue d'un membre de l'équipe.",
    languages: ['Python', 'Discord.py'],
    difficulty: 'difficile',
    status: 'open',
    author: 'sofia.dev',
    memberCount: 3,
    accent: 6,
  },
]);
